"""
Analyzes the project's Python source files and generates a Mermaid architecture diagram.
Output is written to architecture.md.

Usage:
    python analyze_arch.py
"""

import glob
import os
import anthropic


def collect_source_files(root: str = ".") -> dict[str, str]:
    files = {}
    for path in sorted(glob.glob(f"{root}/**/*.py", recursive=True)):
        # Skip virtual environment and cache directories
        parts = path.replace("\\", "/").split("/")
        if any(p in parts for p in [".venv", "__pycache__", ".git"]):
            continue
        with open(path) as f:
            files[path] = f.read()
    return files


def build_context(files: dict[str, str]) -> str:
    return "\n\n".join(
        f"<file path='{path}'>\n{content}\n</file>"
        for path, content in files.items()
    )


def generate_diagram(file_context: str) -> str:
    client = anthropic.Anthropic()

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=2048,
        system="""You are a software architect. Analyze Python codebases and produce clear, accurate Mermaid diagrams.

Your diagrams should show:
- Module/file relationships and imports
- Key functions and which module they belong to
- Data flow between functions (inputs/outputs)
- Any notable dependencies (e.g. external libraries like Streamlit)

Rules:
- Always output valid Mermaid syntax inside a ```mermaid code block
- Use `graph TD` (top-down) layout
- Keep labels concise
- After the diagram, add a short plain-English summary of the architecture (3-5 sentences)""",
        messages=[{
            "role": "user",
            "content": (
                f"{file_context}\n\n"
                "Generate an architecture diagram for this codebase. "
                "Show how the files, functions, and data flow relate to each other."
            )
        }]
    )

    return response.content[0].text


def main():
    print("Collecting source files...")
    files = collect_source_files()

    if not files:
        print("No Python source files found.")
        return

    print(f"Found {len(files)} file(s): {', '.join(files.keys())}")
    print("Generating architecture diagram...")

    context = build_context(files)
    diagram = generate_diagram(context)

    output_path = "architecture.md"
    with open(output_path, "w") as f:
        f.write("# Architecture Diagram\n\n")
        f.write("_Auto-generated by `analyze_arch.py`. Do not edit manually._\n\n")
        f.write(diagram)

    print(f"Diagram written to {output_path}")


if __name__ == "__main__":
    main()
